sudo: false
language: python
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
before_script:
- pip install -e .
- pip install pep8
- pip install nose2
- pip install coverage
- pip install commonconf
- pip install python-coveralls
script:
- pep8 uw_uwnetid/ --exclude=uw_uwnetid/tests
- coverage run --source=uw_uwnetid uw_uwnetid/test.py -v
after_script:
- coveralls
before_deploy:
- find uw_uwnetid/ -name \*.pyc -exec rm {} \;
- echo $TRAVIS_TAG > uw_uwnetid/VERSION
deploy:
  provider: pypi
  server: https://pypi.python.org/pypi
  user: uw-it-aca
  skip_cleanup: true
  password:
    secure: Q1u/kTSlLVTUJn9MF+O2qdxLvA6HN+0G6WT79HPoL+dhgGZ+4oeFLg2DmBnqVL4B3/oJwfbJrE98o8LvQJvvHuxV+q/LscEifk+JiXCCiteBgQyipHrXLUOA0fxZ8plR45nGvNOY3rVuLKxXLBp784VG1FsMwdlaNFK3VLoKmOB94ruJR7FNEPm3u2QNdHH9cm1l8MeXXsyRfbbTRBzuCokb0lUtGHTfilN6348guFnrvTGShwQfeqfPCw9hhOBm6uxbgEMROjQf/o9LXUGqlyJwG06XmlpIFAxG7XKTNDiOGEQ9q/tnnXGOdw7GOwtwdol5Jpp6KUANujpnYuQ6Cb34nkpbW/uRbNUyQN2x327PevHpyOZF84JzYhmwvNEkAsPvG6X62EMw+brkRy5lyJ7IMtx+WPLOfZj9MNnynmmP7Jw6oyuusYqyUy/lY2r15Nr+8IghnnEP4n6YRdQot+17a4k52M4pqljpc4xWtpqCJdl0m06ItU19KZxHtayDNlHU2jiIPX8qwz0jSapCSblaDEZfcs9XvLtn6to2DbN0h95kCWZmdOYqzUdoNZZ4nklFsDbG1c5N8uqppjOpNzegD0A0tQ5hN6SQsqnaLAaJsK0QLZGSb8BcJEqLQjnDl5SNWblMOshFc/fukgpgTMLne91hh5VyY/rAGL4Hk/o=
  on:
    tags: true
condition: $TRAVIS_PYTHON_VERSION = "2.7"
